services:
  client:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: production-stage
      tags:
        - certrust-client:latest
    container_name: client
    networks:
      - net-certrust

  web-server:
    image: nginx:1.25.2-alpine
    container_name: web-server
    tty: true
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net-certrust

networks:
  net-certrust:
