services:
  dev-certrust-web:
    image: certrust-web
    restart: unless-stopped
    container_name: 'dev-certrust-web'
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 24012:24012
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      net-certrust:

networks:
  net-dev-certrust-web:
    driver: bridge
